### ISSUE TITLE
プロダクトバックログ＃１　「プレゼント送り元とあて先情報を登録する」

### ISSUE THREAD

**Issue by ksksan501xx** [ksksan501xx/urus#11]
プロダクトバックログ＃１　「プレゼント送り元とあて先情報を登録する」
■ユーザ：東京の妻または娘さん
■価値：神戸のだんなさん（お父さん）へプレゼントを送る準備ができる

スプリントバックログ

**Comment by tsubouchiy** [comment]
closeしちゃいますね
